// <auto-generated />
namespace TaskManager.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class NumberFIx : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NumberFIx));
        
        string IMigrationMetadata.Id
        {
            get { return "202009192152038_NumberFIx"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
